axios instance with access_token,Redirect
GurgenBaghdasaryan/react pull request #2
Opened 2021-01-20 19:51 UTC by GurgenBaghdasaryan

2021-01-20 20:20 UTC, Ed467016 requested changes

2021-01-20 20:20 UTC, Ed467016 commented on .eslintcache
> +[{"C:\\Users\\37477\\Desktop\\adobe\\src\\index.js":"1","C:\\Users\\37477\\Desktop\\adobe\\src\\App.js":"2","C:\\Users\\37477\\Desktop\\adobe\\src\\reportWebVitals.js":"3","C:\\Users\\37477\\Desktop\
add to gitignore. Its 10 th time im telling you that. Either add in gitignore or not commit this file

2021-01-20 20:20 UTC, Ed467016 commented on src/App.js
>          <Route path="/" component={User} exact />
If user is not logged in he should not be able to go to the user page. Add conditional routing.

2021-01-20 20:20 UTC, Ed467016 commented on src/DataList/index.jsx
> +const DataList = ({ data }) => {
add new line

2021-01-20 20:20 UTC, Ed467016 commented on src/components/Login/index.jsx
>  import axios from "axios";
move to top

2021-01-20 20:20 UTC, Ed467016 commented on src/components/Login/index.jsx
>          localStorage.setItem("access_token", result.data.access_token);
You do not set token in context

2021-01-20 20:20 UTC, Ed467016 commented on src/components/User/index.jsx
> +import axios from "axios";
move to top

2021-01-20 20:20 UTC, Ed467016 commented on src/components/User/index.jsx
>  import { StyledButton } from "./styles";
move to bottom

2021-01-20 20:20 UTC, Ed467016 commented on src/components/User/index.jsx
> +      .catch((err) => history.push("/login"));
remove this. Error can occure because of many reasons. Error doesnt always mean user is unauthenticated

2021-01-20 20:20 UTC, Ed467016 commented on src/httpClient.js
> +import axios from "axios";
You dont use this file, why you have it?

2021-01-21 20:16 UTC, Ed467016 requested changes

2021-01-21 20:16 UTC, Ed467016 commented on src/App.js
> +  const route = () => {
Rewrite

2021-01-21 20:16 UTC, Ed467016 commented on src/components/Login/LoginContent/index.jsx
>  import { StyledInput, StyledParagraph } from "./styles";
Fix imports order

2021-01-21 20:16 UTC, Ed467016 commented on src/components/User/index.jsx
> +import DataList from "./DataList";
Fix imports order. First packages then components after css

2021-01-21 20:16 UTC, Ed467016 commented on src/components/Login/LoginContent/styles.js
> +  text-indent: 5px ;
remove space

2021-01-25 18:58 UTC, Ed467016 approved these changes

2021-01-25 19:13 UTC, Ed467016 requested changes

2021-01-25 19:13 UTC, edotnet commented on src/App.js
> +          <Redirect to="/" />
Add from prop

2021-01-25 19:13 UTC, Ed467016 commented on src/UserContext/index.js
> +  const [token, setToken] = useState(getToken);
Set token inside useEffect

2021-01-25 19:13 UTC, Ed467016 commented on src/UserContext/index.js
> +  const [disable, setDisable] = useState(false);
Move this into Login component. Rename to `[error, setError]`

2021-01-25 19:13 UTC, Ed467016 commented on src/components/Login/index.jsx
>    const values = {
Remove this object

2021-01-25 19:13 UTC, Ed467016 commented on src/components/User/index.jsx
> +          Authorization: `token ${getToken}`,
Shouldnt `token` be `Bearer`? @GurgenBaghdasaryan Confirm with Arayik or Hovo

2021-01-25 19:13 UTC, Ed467016 commented on src/components/User/index.jsx
> +    setDisable("");
SetDisable was boolean now you set it to empty string. Its incorrect

2021-01-25 19:13 UTC, Ed467016 commented on src/components/User/DataList/index.jsx
> +        {data.map((i) => (
Add data checking against undefined, since it can be undefined if api response is not received yet

2021-01-25 19:13 UTC, Ed467016 commented on src/components/shared/Button/index.jsx
> +  return <StyledButton onClick={clickEvent}>Login</StyledButton>;
You created reusable component with fixed content `Login`. Get button content via props. See `children` prop

2021-01-25 19:22 UTC, GurgenBaghdasaryan commented on src/App.js
> +          <Redirect to="/" />
what do you mean?

2021-01-25 20:37 UTC, Ed467016 commented on src/App.js
> +          <Redirect to="/" />
It should look like `<Redirect from="/asdasd" to="/" />`. To tell router from which router it should redirect to `/`

2021-01-25 21:00 UTC, Ed467016 requested changes

2021-01-25 21:00 UTC, Ed467016 commented on src/UserContext/index.js
>    const getToken = localStorage.getItem("access_token");
Move into useeffect

2021-01-25 21:00 UTC, Ed467016 commented on src/App.js
> +          <Redirect path="/" to="/login" />
Change path to *

2021-01-25 21:00 UTC, Ed467016 commented on src/components/Login/index.jsx
>    const values = {
Remove this object

2021-01-25 21:00 UTC, Ed467016 commented on src/components/shared/Button/index.jsx
> +  return <StyledButton onClick={clickEvent}>{children}</StyledButton>;
Make sure you know what `children` is

2021-01-25 21:20 UTC, Ed467016 approved these changes

2021-01-27 13:27 UTC, Ed467016 requested changes

2021-01-27 13:27 UTC, Ed467016 commented on src/App.js
> +import { useSelector } from "react-redux";
import next to useDispatch

2021-01-27 13:27 UTC, Ed467016 commented on src/App.js
>  import "./App.css";
import css in end

2021-01-27 13:27 UTC, Ed467016 commented on src/App.js
> +    const auth = useSelector((state) => state.auth.token);
you are receiving here `token` from store why the variable name is `auth`?

2021-01-27 13:27 UTC, Ed467016 commented on src/App.js
> +          <Route path="/login" component={Login} />
add exact

2021-01-27 13:27 UTC, Ed467016 commented on src/components/Login/LoginContent/index.jsx
> +import { useSelector } from "react-redux";
import packages first

2021-01-27 13:27 UTC, Ed467016 commented on src/components/Login/LoginContent/index.jsx
> +  const token = useSelector((state) => state.token);
wrong selector. this will not return token

2021-01-27 13:27 UTC, Ed467016 commented on src/components/User/index.jsx
>  import { useHistory } from "react-router-dom";
Import packages on top

2021-01-27 13:27 UTC, Ed467016 commented on src/components/User/index.jsx
> +  const getToken = localStorage.getItem("access_token");
Move into useEffect

2021-01-27 13:27 UTC, Ed467016 commented on src/components/User/index.jsx
> +        history.push("/user");
dont redirect user

2021-01-27 14:08 UTC, merged